---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)

```

```{css}

```

## My Data - People Walking

While on the bus/in a car, I observed the people walking by and whether or not they were walking a dog. If they were, I counted how many dogs they had and noted the colour of one of them. 

```{r}

library(tidyverse)
library(ggplot2)
library(readr)


logged_data <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRUiDli6_FRCoFlTSPfcJyC54yEx864HDa9PUB9DWofesJjIrQ8RMQfvfJQycf4AoNZ3tzhMRxI8tJk/pub?gid=2012152271&single=true&output=csv")

latest_data <- as.data.frame(logged_data) 
  
latest_data <- logged_data %>%
  rename(
    dog_yes_no = 2,    
    dog_number = 3,
    dog_colour = 4
  )

#my values
num_sightings <- latest_data$dog_yes_no %>%
  length()


mean_dogs <- mean(latest_data$dog_number, na.rm = TRUE) %>%
  round(1)


#my charts


latest_data_clean <- na.omit(latest_data) 

ggplot(latest_data_clean, aes(x = factor(dog_colour))) +
  geom_bar(fill = "#F48668") +  
  labs(
    title = "Bar Chart of Dog Colours",
    x = "Colour of Dogs",
    y = "Count"
  ) +
  theme_minimal()

ggplot(latest_data, aes(x = (dog_yes_no))) +
  geom_bar(fill = "lavender") +  
  labs(
    title = "Was There a Dog?",
    x = "Yes/No",
    y = "Count"
  ) +
  theme_minimal()

paste0("The mean number of dogs spotted in all ", num_sightings, " observations was ", mean_dogs, ".")
```



